const html = `<!DOCTYPE html>
<head>
    <style>
        * {
            font-family: sans-serif;
        }
        h1 {
            font-weight: 300;
        }
    </style>
</head>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.....</p>
</body>`

async function handleRequest(request) {
  return new Response(html, {
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },
  })
}

addEventListener("fetch", event => {
  return event.respondWith(handleRequest(event.request))
})