# serverless.yml

service:
  name: mauricionr
  config:
    accountId: "4e988bf7025e2e3d0a368b674ab6de4f"
    zoneId: "d4d1cee352e1e95bfb4ebda0e1284814"

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  index:
    name: index-production
    worker: index
    script: index
    resources:
      kv:
        - variable: TODOS
          namespace: TODOS
    events:
      - http:
          url: mauricionr.com.br
          method: GET