name = "distance"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
workers_dev = false
route = "mauricionr.com.br/distance*"
vars = { NODE_ENV = "production", GOOGLE_MAPS_API_KEY = "" }