account_id = "CF_ACCOUNT_ID"
name = "index"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }

[env.production]
workers_dev = false
route = "https://mauricionr.com.br/*"
zone_id = "CF_ZONE_ID"