account_id = "CF_ACCOUNT_ID"
name = "index"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }

[env.production]
workers_dev = false
route = "mauricionr.com.br*"
kv_namespaces = [
  { binding = "__index", id = "9b15b22a1a2f4f76a654a1ee1fbe558e", preview_id = "68a2bef264a942139b04d87c9d02d10a" }
]