name = "blog"
type = "javascript"
account_id = ""
workers_dev = true
route = ""

[env.production]
workers_dev = false
route = "mauricionr.com.br/blog*"
vars = { NODE_ENV = "production", HOST = "https://blog.mauricionr.com.br" }